### ISSUE TITLE
Oracle returns wrong price with the tokens which have less than 18 decimals when using ETH-based aggregator

### ISSUE THREAD

**Issue by WelToHackerLand** [LodestarFinance/lodestar-protocol#10]
### Title
Oracle returns wrong price with the tokens which have less than 18 decimals when using ETH-based aggregator

### Affected smart contract
https://github.com/LodestarFinance/lodestar-protocol/blob/relaunch-candidate/contracts/Oracle/PriceOracleProxyETH.sol#L114-L118
### Description 
Function `getUnderlyingPrice()` is used to get the price of 1 wei of underlying token in wei of ETH. 
```solidity=
else if (address(aggregatorInfo.source) != address(0)) {
bool sequencerStatus = getSequencerStatus(sequencerAddress);
uint256 price = getPriceFromChainlink(aggregatorInfo.source);
...
} else if (aggregatorInfo.base == AggregatorBase.ETH) {
    return price;
}
```
In case the `aggregatorInfo.base == AggregatorBase.ETH`, the oracle return the value of `price` which is fetched directly from chainlink oracle. 
```solidity=
function getPriceFromChainlink(AggregatorV3Interface aggregator) internal view returns (uint256) {
    (, int256 price, , , ) = aggregator.latestRoundData();
    require(price > 0, "invalid price");

    // Extend the decimals to 1e18.
    return uint256(price) * 10 ** (18 - uint256(aggregator.decimals()));
}
```
Unfortunately the price of chainlink oracle returns the value of 1 token asset (not 1 wei token) to ETH (not wei ETH). Take a look at this [USDC/ETH](https://etherscan.io/address/0x986b5E1e1755e3C2440e960477f25201B0a8bbD4#readContract) price feed for more details. If u take the `lastTestAnswer` divide with `decimals = 1e18`, u will receive the value of 1 USDC to ETH instead of 1 weiUSDC to 1 weiETH. This will make an inconsistence between 2 cases when the aggregatorInfo.base = ETH (return price in token) and aggregatorInfo.base = USD (return price in wei). 

Furthermore the value returned from function `getUnderlyingPrice()` is used by Comptroller to determine the value of cToken. It can lead to some really bad scenario for the protocol when user can borrow more / borrow less because of the incorrect price value.

### Attack Scenario 
1. At the current time, 1 USDC = 1$ USD, 1 ETH = 1000$ USD
2. Function `getUnderlyingPrice` is called with **cToken** = cUSDC, to calculate the price of USDC (to ETH). And aggregator of USDC is chainlink price feeds of USDC-ETH
3. Firstly, `price = getPriceFromChainlink(aggregatorInfo.source)` with aggregatorInfo.source is aggregator USDC-ETH of chainlink. So price = 1e15 (since decimals of aggregator = 18, and data price feed = 1e15)
4. When it check `aggregatorInfo.base == AggregatorBase.ETH`, it returns the price (1e15)
5. For example, comptroller needs to convert 1e6 wei USDC to ETH, using this price to calculate value USDC to ETH, and get 1e6 * 1e15 / 1e18 = 1000 wei ETH. 
6. But USDC has 6 decimals, 1e6 wei USDC should be 1e15 wei ETH (~1$ USD) instead of 1000 wei ETH 

### Recommendation
Consider to modify the case when aggregatorInfo.base == AggregatorBase.ETH as follows: 
```solidity=
else if (aggregatorInfo.base == AggregatorBase.ETH) {
    uint256 underlyingDecimals = EIP20Interface(CErc20(cTokenAddress).underlying()).decimals();
    return price * 10 ** (18 - underlyingDecimals)
}
```

**Comment by 0xAppo** [comment]
This issue has been resolved at commit hash: 7b519c75180f153e5aa38d94beb0d8dcdb06021e. Good find.
