### ISSUE TITLE
Supply caps of CToken can be set to lower than current supply by mistake

### ISSUE THREAD

**Issue by WelToHackerLand** [LodestarFinance/lodestar-protocol#11]
### Title
Supply caps of CToken can be set to lower than current supply by mistake

### Affected smart contract
https://github.com/LodestarFinance/lodestar-protocol/blob/relaunch-candidate/contracts/Comptroller.sol#L1114-L1129

### Description
Function `_setMarketBorrowCaps` is used to set the borrow caps of CTokens. But in the function, there is no check that `newSupplyCaps` must be greater than the current supply of CTokens. Then the **admin** or **supplyCapGuardian** can set mistakenly the supply caps to be lower than the current total supply of CTokens.
```solidity=
function _setMarketSupplyCaps(CToken[] calldata cTokens, uint[] calldata newSupplyCaps) external {
    require(
        msg.sender == admin || msg.sender == supplyCapGuardian,
        "only admin or borrow cap guardian can set borrow caps"
    );

    uint numMarkets = cTokens.length;
    uint numSupplyCaps = newSupplyCaps.length;

    require(numMarkets != 0 && numMarkets == numSupplyCaps, "invalid input");

    for (uint i = 0; i < numMarkets; i++) {
        supplyCaps[address(cTokens[i])] = newSupplyCaps[i];
        emit NewSupplyCap(cTokens[i], newSupplyCaps[i]);
    }
}
```

### Recommendation
Add a check that new supply caps must be greater than the current supply
```solidity=
for (uint i = 0; i < numMarkets; i++) {
    require(newSupplyCaps[i] > cTokens[i].totalSupply());
    supplyCaps[address(cTokens[i])] = newSupplyCaps[i];
    emit NewSupplyCap(cTokens[i], newSupplyCaps[i]);
}
```

**Comment by 0xAppo** [comment]
This is by design. The intent being to allow for the supply cap to be set below the current amount of deposits such that no additional deposits can take place in the markets until the amount of deposits is back below the cap.
