### ISSUE TITLE
Borrow caps of CToken can be set to lower than the current total borrows by mistake

### ISSUE THREAD

**Issue by WelToHackerLand** [LodestarFinance/lodestar-protocol#12]
### Title
Borrow caps of CToken can be set to lower than the current total borrows by mistake

### Affected smart contract
https://github.com/LodestarFinance/lodestar-protocol/blob/relaunch-candidate/contracts/Comptroller.sol#L1074-L1089

### Description
Function `_setMarketBorrowCaps` is used to set the borrow caps of CTokens. But in the function, there is no check that `newBorrowCaps` must to be greater than the current borrows of CTokens. Then the **admin** or **borrowCapGuardian** can set mistakenly the borrow caps to be lower than the current total borrows of CTokens.
```solidity=
function _setMarketBorrowCaps(CToken[] calldata cTokens, uint[] calldata newBorrowCaps) external {
    require(
        msg.sender == admin || msg.sender == borrowCapGuardian,
        "only admin or borrow cap guardian can set borrow caps"
    );

    uint numMarkets = cTokens.length;
    uint numBorrowCaps = newBorrowCaps.length;

    require(numMarkets != 0 && numMarkets == numBorrowCaps, "invalid input");

    for (uint i = 0; i < numMarkets; i++) {
        borrowCaps[address(cTokens[i])] = newBorrowCaps[i];
        emit NewBorrowCap(cTokens[i], newBorrowCaps[i]);
    }
}
```

### Recommendation
Add a check that new borrow caps must be greater than the current total borrows
```solidity=
for (uint i = 0; i < numMarkets; i++) {
    require(newBorrowCaps[i] > cTokens[i].totalBorrows());
    borrowCaps[address(cTokens[i])] = newBorrowCaps[i];
    emit NewBorrowCap(cTokens[i], newBorrowCaps[i]);
}
```

**Comment by 0xAppo** [comment]
This is by design. The intent being to allow for the borrow cap to be set below the current amount of borrows such that no additional borrowing can take place in the markets until the amount of borrows is back below the cap.
