### ISSUE TITLE
Unchecked return value transferFrom 

### ISSUE THREAD

**Issue by maarcweiss** [LodestarFinance/lodestar-protocol#22]
## TITLE (Unchecked return value transferFrom )
While performing a transfer in USDC, either you should use safeTransferFrom or check it's return value according to it's IERC20 interface. USDC does return a boolean if something unintended has happened during the transaction and the funds would have not been sent. It is a rare case, that is why it is a medium and not a high. 

https://github.com/PlutusDAO/plvGLP-looper/blob/9cb8dbc16183e7526382a07db259e61a1e1b191c/contracts/Ploopy.sol#L108

## SEVERITY (either high or medium, see the rules)
Medium, not very likely, but can have unintended consequences if it happens

## A LINK TO THE GITHUB ISSUE
https://github.com/PlutusDAO/plvGLP-looper/blob/9cb8dbc16183e7526382a07db259e61a1e1b191c/contracts/Ploopy.sol#L108

## SOLUTION
Add require statement:

     //BEFORE

         USDC.transferFrom(data.user, msg.sender, data.borrowedAmount);

       //AFTER

           require(USDC.transferFrom(data.user, msg.sender, data.borrowedAmount), "wrong transfer");

**Comment by WelToHackerLand** [comment]
It seems like USDC doesn't return false if any unintended has happened, it reverts the tx instead. U can take a look at
https://etherscan.io/address/0xb7277a6e95992041568d9391d09d0122023778a2#code

**Comment by 0xAppo** [comment]
The solution to this issue is generally to use the safeERC20 library, and this issue/solution is marked as planned in #5
