### ISSUE TITLE
CastVote can be done even proposal is in pending state

### ISSUE THREAD

**Issue by pavankv241** [LodestarFinance/lodestar-protocol#26]
SEVERITY :- 
Medium

castVoteInternal() had [check](https://github.com/LodestarFinance/lodestar-protocol/blob/relaunch-candidate/contracts/Governance/GovernorBravoDelegate.sol#L271) to whether proposal id is active or not, but no check to whether proposal is in pending state or not . [propose()](https://github.com/LodestarFinance/lodestar-protocol/blob/relaunch-candidate/contracts/Governance/GovernorAlpha.sol#L136) cannot call if latestProposalId is not pending and active but CastVote() can be done .

Recommendation 
require(state(proposalId)!= ProposalState.Pending, "");

**Comment by 0xAppo** [comment]
As shown in the state function in the Governor contract, the only possible states for a proposal to be in are: canceled, pending, active, defeated, successful, executed, expired, and queued. The only one of these states where voting should be allowed to take place is during the active state, and the check linked here explicitly requires for the proposal state to be active to accomplish this. The change suggested here would allow for voting in all states except for pending, which is not the intended behavior. As for your second point, I think you've gotten some things turned around here. A user cannot make a new proposal if their latest proposal is either active or pending. The two are independent of one another.
