### ISSUE TITLE
Chainlink's latestRoundData might return stale results

### ISSUE THREAD

**Issue by rajatbeladiya** [LodestarFinance/lodestar-protocol#3]
## Affected Smart contracts
PriceOracleProxyETH.sol

## Severity:
Medium

## Description:

https://github.com/LodestarFinance/lodestar-protocol/blob/cfca1ae275d023a02198798bbcb24b2a1f646776/contracts/Oracle/PriceOracleProxyETH.sol#L134-L135

here lodestar using Chainlink's latestRoundData API, but there is no check if the return value indicates stale data. This could lead to stale prices according to the Chainlink documentation:

* https://docs.chain.link/docs/historical-price-data/#historical-rounds

## Recommendation:

add checks for stale data

```
(uint80 roundId, int256 price, uint256 timestamp, uint256 answeredInRound, ) = aggregator.latestRoundData();
 require(price > 0, 'invalid price');
require(answeredInRound >= roundId, 'stale price');
require(timestamp != 0, 'round not complete');

```

**Comment by rotcivegaf** [comment]
Don't specified **Attack scenario**

**Comment by rajatbeladiya** [comment]
@rotcivegaf  it's crucial to remember that not every issue can be framed as an attack scenario, and our ultimate goal should be to improve the overall security and functionality of the smart contract in question.
In this particular scenario, it is a critical problem that must be addressed by the developers to ensure the accuracy and reliability of the smart contract.
let the committee decide.
