### ISSUE TITLE
Allow borrowCap to be filled fully

### ISSUE THREAD

**Issue by rajatbeladiya** [LodestarFinance/lodestar-protocol#4]
## Affected Smart Contracts:
Comptroller.sol

## Severity:
Medium

## Description:

https://github.com/LodestarFinance/lodestar-protocol/blob/cfca1ae275d023a02198798bbcb24b2a1f646776/contracts/Comptroller.sol#L405

Here the condition should be '<=', not '<' to allow filling the cap fully:
require(nextTotalBorrows < borrowCap, "market borrow cap reached");

## Recommendation:
change to `require(nextTotalBorrows <= borrowCap, "market borrow cap reached”);`

**Comment by 0xAppo** [comment]
Noted, the decimal precision of all assets makes this difference negligible in practice. Issue severity also low at most.
