### ISSUE TITLE
Sushi oracle is vulnerable to use as a price feed

### ISSUE THREAD

**Issue by WelToHackerLand** [LodestarFinance/lodestar-protocol#7]
# Sushi oracle is vulnerable to use as a price feed

### Title
Sushi oracle is vulnerable to be used as a price feed 

### Affected smart contract
https://github.com/LodestarFinance/lodestar-protocol/blob/relaunch-candidate/contracts/Oracle/SushiOracle.sol#L35-L40

### Description
Function `price` of SushiOracle is implemented as follow: 
```solidity=
/// url = https://github.com/LodestarFinance/lodestar-protocol/blob/relaunch-candidate/contracts/Oracle/SushiOracle.sol#L35-L40
function price () public view returns (uint256 price) {

    uint256 balanceA = getTokenBalance(tokenA);
    uint256 balanceB = getTokenBalance(tokenB);

    price = (balanceA * 1e18) / balanceB;

    return price;
}
```
Since it uses the current balance of tokens in the pool as the material for the price calculation, it could be manipulated easily by the attacker via `flashloan` mechanism. Then attacker can attack the contracts which use this oracle. 

### Attack scenario
Since I didn't see any contracts in the repo with the given commit-hash uses this price feed, I assume that the protocol want to integrate this oracle in the future (Sushi oracle is still in the scope, so I guess the team have intention in integrating this contract)

1. The attacker had an amount of tokenA as collateral.
2. The attacker called `sushi.swap()` to flashloan an enormous amount of tokenA to decrease the portion of tokenA compare to tokenB which lead to the fall in price of tokenB. 
3. In flashloan's callback function, the attacker's contract called `CToken.borrow()` to buy a lot of tokenB (more than expected) because of the cheap price.
4. Eventually the attacker transfered tokenA plus the fee back to the sushi's pool and finished the attack strategy.

### Recommendation
Take a look at the uniswap docs when you want to integrate the oracle into your contracts 
https://docs.uniswap.org/contracts/v2/guides/smart-contract-integration/building-an-oracle

**Comment by 0xAppo** [comment]
This issue is documented and acknowledged in the audit performed by Solidity Finance, the Sushi oracle contract is used only for front end display of the LODE price and is not used for pricing data in any of the markets.
